name: peanut
description: priceofpeanuts
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  http: ^0.12.0
  html: ^0.14.0+2
  gbk_codec: ^0.3.1+3
  logging: ^0.11.3+2

dev_dependencies:
